#!/usr/bin/env ruby

require File.expand_path(File.join(File.dirname(__FILE__), '..', 'lib', 'fogsplode'))

argv = ARGV.map {|command| command.downcase}

case argv[0]
when 'init'
  subgem = argv[1]

  Fogsplode.init(subgem)

  Fogsplode.gemfiles(subgem)
  Fogsplode.open_source(subgem)
  Fogsplode.readme(subgem)
  Fogsplode.tasks(subgem)
  Fogsplode.travis(subgem)
else
  "Unknown command"
end
