#!/usr/bin/env ruby

require File.expand_path(File.join(File.dirname(__FILE__), '..', 'lib', 'fogsplode'))

argv = ARGV.map {|command| command.downcase}

case argv[0]
when 'init'
  subgem = argv[1]

  # initialize gem
  `bundle gem #{subgem}`
  Dir.chdir(subgem)

  `git remote add origin git@github.com:fog/#{subgem}.git`

  # gemfiles
  Dir.mkdir('gemfiles')
  File.open('gemfiles/Gemfile-ruby-1.8.7', 'w') do |file|
    file.write <<-GEMFILE
source "https://rubygems.org"

gem 'mime-types', '~> 1.16'
gem 'nokogiri', '~> 1.5.11'

gemspec :path => "../"
    GEMFILE
  end
  File.open('gemfiles/Gemfile-ruby-1.9', 'w') do |file|
    file.write <<-GEMFILE
source "https://rubygems.org"

gem 'json', '~> 1.8'
gem 'mime-types', '~> 2.6', '>= 2.6.2'
gem 'nokogiri', '~> 1.6.8'

gemspec :path => "../"
    GEMFILE
  end
  File.open('gemfiles/Gemfile-ruby-2.0', 'w') do |file|
    file.write <<-GEMFILE
source "https://rubygems.org"

gem 'mime-types', '~> 3.1'
gem 'nokogiri', '~> 1.6.8'

gemspec :path => "../"
    GEMFILE
  end
  File.open('gemfiles/Gemfile-edge', 'w') do |file|
    file.write <<-GEMFILE
source "https://rubygems.org"

gem 'mime-types', '~> 3.1'
gem 'nokogiri', '~> 1.6.8'

gem "fog-core", :github => "fog/fog-core"
# gem "fog-json", :github => "fog/fog-json"
# gem "fog-xml", :github => "fog/fog-xml"

gemspec :path => "../"
    GEMFILE
  end

  # tasks/rakefile

  # .travis.yml
  File.open('.travis.yml', 'w') do |file|
    file.write <<-TRAVIS
language: ruby
sudo: false
script: bundle exec rake test
matrix:
  fast_finish: true
  include:
  - rvm: 1.8.7
    gemfile: gemfiles/Gemfile-ruby-1.8.7
  - rvm: 1.9.3
    gemfile: gemfiles/Gemfile-ruby-1.9
  - rvm: 2.0.0
    gemfile: gemfiles/Gemfile-ruby-2.0
  - rvm: 2.1.1
    gemfile: Gemfile
  - rvm: 2.2.0
    gemfile: Gemfile
  - rvm: 2.3.0
    gemfile: Gemfile
  - rvm: 2.3.0
    gemfile: gemfiles/Gemfile-edge
  - rvm: jruby-18mode
    gemfile: gemfiles/Gemfile-ruby-1.8.7
  - rvm: jruby-19mode
    gemfile: gemfiles/Gemfile-ruby-1.9
  - rvm: jruby-head
    gemfile: Gemfile
  allow_failures:
    - rvm: jruby-head
notifications:
  email: false
TRAVIS
  end

  # README
  File.open('README.md', 'w') do |file|
    file.write <<-README
# #{subgem}

![Gem Version](https://badge.fury.io/rb/fog-#{subgem}.svg)
[![Build Status](https://travis-ci.org/fog/fog-#{subgem}.svg?branch=master)](https://travis-ci.org/fog/fog-#{subgem})
[![Dependency Status](https://gemnasium.com/fog/fog-#{subgem}.svg)](https://gemnasium.com/fog/fog-#{subgem})
[![Test Coverage](https://codeclimate.com/github/fog/fog-#{subgem})](https://codeclimate.com/github/fog/fog-#{subgem})
[![Code Climate](https://codeclimate.com/github/fog/fog-#{subgem}.svg)](https://codeclimate.com/github/fog/fog-#{subgem})

## Installation

Add this line to your application's Gemfile:

```ruby
gem '#{subgem}'
```

And then execute:

    $ bundle

Or install it yourself as:

    $ gem install #{subgem}

## Usage

Before you can use fog-#{subgem}, you must require it in your application:

  ```ruby
require 'fog/fog-#{subgem}'
```

## Development

After checking out the repo, run `bin/setup` to install dependencies. You can also run `bin/console` for an interactive prompt that will allow you to experiment. Run `bundle exec fogsplode` to use the gem in this directory, ignoring other installed copies of this gem.

To install this gem onto your local machine, run `bundle exec rake install`. To release a new version, update the version number in `version.rb`, and then run `bundle exec rake release`, which will create a git tag for the version, push git commits and tags, and push the `.gem` file to [rubygems.org](https://rubygems.org).

## Getting Help

* [General Documentation](http://fog.io).
* [Provider Specific Documentation](http://fog.io/about/provider_documentation.html).
* Ask specific questions on [Stack Overflow](http://stackoverflow.com/questions/tagged/fog)
* Report bugs and discuss potential features in [Github issues](https://github.com/fog/fog/issues).

## Contributing

Please refer to [CONTRIBUTING.md](https://github.com/fog/fog/blob/master/CONTRIBUTING.md).

## License

Please refer to [LICENSE.md](https://github.com/fog/fog/blob/master/LICENSE.md).
README
  end

  `git commit -m "fogsplode init"`

  require 'osrcry'
  Osrcry::Contributing.execute
  Osrcry::Contributors.execute
  Osrcry::License.execute

  `git commit -m "add open source bits"`
else
  "Unknown command"
end
